In [1]:
#import Dependencies
import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
#create austin crime df
crime_df = pd.read_csv('2016_Annual_Crime_Data.csv',low_memory=False)
crime_df.head()

,GO Primary Key,Council District,GO Highest Offense Desc,Highest NIBRS/UCR Offense Description,GO Report Date,GO Location,Clearance Status,Clearance Date,GO District,GO Location Zip,GO Census Tract,GO X Coordinate,GO Y Coordinate
0,201610188.0,8.0,AGG ASLT ENHANC STRANGL/SUFFOC,Agg Assault,1-Jan-16,8600 W SH 71 ...,C,12-Jan-16,D,78735.0,19.08,3067322.0,10062796.0
1,201610643.0,9.0,THEFT,Theft,1-Jan-16,219 E 6TH ST ...,C,4-Jan-16,G,78701.0,11.00,3114957.0,10070462.0
2,201610892.0,4.0,AGG ROBBERY/DEADLY WEAPON,Robbery,1-Jan-16,701 W LONGSPUR BLVD ...,N,3-May-16,E,78753.0,18.23,3129181.0,10106923.0
3,201610893.0,9.0,THEFT,Theft,1-Jan-16,404 COLORADO ST ...,N,22-Jan-16,G,78701.0,11.00,3113643.0,10070357.0
4,201611018.0,4.0,SEXUAL ASSAULT W/ OBJECT,Rape,1-Jan-16,NaN,C,10-Mar-16,E,78753.0,18.33,NaN,NaN

In [3]:
#clean-up data
crime_df = crime_df.dropna(how="any")
crime_df.count()

GO Primary Key                           34885
Council District                         34885
GO Highest Offense Desc                  34885
Highest NIBRS/UCR Offense Description    34885
GO Report Date                           34885
GO Location                              34885
Clearance Status                         34885
Clearance Date                           34885
GO District                              34885
GO Location Zip                          34885
GO Census Tract                          34885
GO X Coordinate                          34885
GO Y Coordinate                          34885
dtype: int64

In [4]:
#dataframe with crime by zipcodes
crime_df = pd.DataFrame(crime_df["GO Location Zip"].value_counts())
crime_df = crime_df.reset_index()
crime_df = crime_df.rename(columns = {"GO Location Zip":"crime reports","index":"zip_code" })
crime_df.head()

   zip_code  crime reports
0   78741.0           3121
1   78753.0           2904
2   78704.0           2380
3   78758.0           2281
4   78745.0           2108

In [5]:
crime_df.to_csv("crime.csv")